### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SpiritCroc/DarkCroc-Android-theme#13]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by SpiritCroc** [comment]
I know, but since I don't use Substratum anymore, I don't think I'll update this theme anymore (and F-Droid will only pick up fastlane changes if there is a new release).

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.

**Comment by SpiritCroc** [comment]
As far as I know, the one who opens the issue can close it too, but as you wish.
