### ISSUE TITLE
Notifications unreadable

### ISSUE THREAD

**Issue by RantSomeWhere** [SpiritCroc/DarkCroc-Android-theme#3]
Hello,

When applying your theme with all the colors set to black, my notifications become unreadable. It seems that your theme does not change the font color and black letters on a black background is, of course, not readable at all.

**Comment by RantSomeWhere** [comment]
Wow, that was stupid. 
The notifs become readable again after a reboot. Closing...

**Comment by SpiritCroc** [comment]
Great to hear you solved it.
In most cases, restarting SystemUI should be enough to recreate notifications after a theme change.
Usually, Substratum does this for you, but it seems to not always work reliably.

**Comment by RantSomeWhere** [comment]
Yes, I always have to restart SystemUI manually for some reason, and even that did not make the notifs readable. Strange behavior, but at least it's working now.

Great theme, by the way!
