### ISSUE TITLE
Share menu is unthemed which causes all the labels to be invisible

### ISSUE THREAD

**Issue by poperigby** [SpiritCroc/DarkCroc-Android-theme#5]
Like this: https://photos.app.goo.gl/CfUrobyw5r1Dge89A

**Comment by SpiritCroc** [comment]
Fine here. I can't help without further information, please check https://github.com/SpiritCroc/DarkCroc-Android-theme/blob/9.0-substratum/about.md

**Comment by poperigby** [comment]
ROM version: stock Moto G5 Plus
Android version: 8.1
Substratum version: 1015
Theme version: 7.7
Overlay variants: 
-Android system
-Bluetooth
-Call management
-Default print service
-Files
-Package installation
-Phone
-Phone services
-Settings
-System UI

**Comment by SpiritCroc** [comment]
I think you are posting in the wrong github repository, the latest DarkCroc theme version is 1.2 and is for android 9+ only.

I assume you are using Default Dark on a device without the required exposure commits to make the share menu dark, so please try out the legacy variants if that is the case to ensure readability.
