### ISSUE TITLE
Android Pie Contacts white on white

### ISSUE THREAD

**Issue by mrbluecoat** [SpiritCroc/DarkCroc-Android-theme#7]
On Android Pie using the default Google Contacts app, the email, phone, etc shows up white on white:  https://ibb.co/NsX5ccC

**Comment by SpiritCroc** [comment]
Which overlays do you have applied?
(Please consider also adding more relevant information to your bug report next time as described here https://github.com/SpiritCroc/DarkCroc-Android-theme/blob/9.0-substratum/about.md )

**Comment by mrbluecoat** [comment]
Oh, my apologies:

- LineageOS
- Android v.9 (PQ2A.190205.001)
- model HTC 10 (pme)
- theme platform: dynamic overlays (OMS)
- substratum v.1015
- app theme set to: Dark
- DarkCroc Theme (v.1.3) overlays: all selected, including Contacts com.android.contacts [1.7.31]

**Comment by SpiritCroc** [comment]
1. Are you sure you are using Google Contacts app? I never touched that one, and I would expect the google contacts app to replace the AOSP one, so the com.android.contacts overlay shouldn't be available in that scencario.
2. LineageOS has their own dark theming "solution" which doesn't work too well together with themes targetting pure AOSP applications. As an easy workaround, you should be able to go to lineage settings and select a dark theme (I think it was in display settings last time I saw it), so substratum themes are applied on top of an already dark lineage theme and issues like this should be avoided. Could you please try that out and report back?

**Comment by mrbluecoat** [comment]
Sorry, my mistake - I was using stock/AOSP Contacts (openGapps micro).  I switched to Google Contacts as a solution.  Thanks!
